name: Deploy new data

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_data]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: download covid19-scraping-rust
      run: |
        curl -LO https://github.com/stop-covid19-kyoto/covid19-scraping-rust/releases/download/v2.0.0/covid19-scraping-rust-linux-x86_64.tar.gz
        tar -zxvf covid19-scraping-rust-linux-x86_64.tar.gz
    - name: Run scraping tool
      env:
        SERVER: ${{ secrets.SERVER }}
        PORT: ${{ secrets.PORT }}
        AUTH_URL: ${{ secrets.AUTH_URL }}
        TOKEN_URL: ${{ secrets.TOKEN_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        KYOTO_ADDR: ${{ secrets.KYOTO_ADDR }}
        KYOTO_ADDR_2: ${{ secrets.KYOTO_ADDR }}
        KYOTO_ADDR_3: ${{ secrets.KYOTO_ADDR }}
        MY_ADDR:  ${{ secrets.MY_ADDR }}
      run: TZ="Asia/Tokyo" ./covid19-scraping-rust --server ${SERVER} --port ${PORT} --account ${MY_ADDR} --auth-url ${AUTH_URL} --token-url ${TOKEN_URL} --client-id ${CLIENT_ID} --client-secret ${CLIENT_SECRET} --refresh-token ${REFRESH_TOKEN} --query "OR FROM ${KYOTO_ADDR} OR FROM ${MY_ADDR} OR FROM ${KYOTO_ADDR_2} OR FROM ${KYOTO_ADDR_3} X-GM-RAW \"has:attachment\""
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: gh-pages
        allow_empty_commit: false
